# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

pod 'Flutter', :path => '../.symlinks/flutter/ios'
pod 'flutter_nfc_kit', :path => '../.symlinks/plugins/flutter_nfc_kit/ios'